# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddArea
                                 A QGIS plugin
 This Plugin adds an area column to your polygon shapefiles in QGIS in Hectares
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-22
        copyright            : (C) 2026 by n/a
        email                : j.frauenfelder@me.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddArea class from file AddArea.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AddArea import AddArea
    return AddArea(iface)
