# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddArea
                                 A QGIS plugin
 This Plugin adds an area column to your polygon shapefiles in QGIS in Hectares
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by n/a
        email                : j.frauenfelder@me.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .AddArea_dialog import AddAreaDialog
import os.path

import math
from qgis.core import QgsField, QgsDistanceArea, QgsProject, QgsVectorLayer, QgsWkbTypes, Qgis
from PyQt5.QtCore import QVariant

class AddArea:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AddArea_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AddArea')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AddArea', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/AddArea/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AddArea'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&AddArea'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        bar = self.iface.messageBar()
        layer = self.iface.activeLayer()

        if layer is None:
            bar.pushMessage('Area_ha', 'No active layer — select a polygon layer first.', level=Qgis.Warning, duration=5)
            return
        if not isinstance(layer, QgsVectorLayer):
            bar.pushMessage('Area_ha', 'Active layer is not a vector layer.', level=Qgis.Warning, duration=5)
            return
        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            bar.pushMessage('Area_ha', 'Active layer is not a polygon layer.', level=Qgis.Warning, duration=5)
            return

        field_name = 'Area_ha'
        da = QgsDistanceArea()
        da.setSourceCrs(layer.crs(), QgsProject.instance().transformContext())
        ellipsoid = QgsProject.instance().ellipsoid()
        if not ellipsoid or not da.setEllipsoid(ellipsoid):
            da.setEllipsoid('EPSG:7030')

        if layer.fields().indexFromName(field_name) == -1:
            layer.dataProvider().addAttributes([QgsField(field_name, QVariant.Double, 'double', 15, 4)])
            layer.updateFields()

        field_index = layer.fields().indexFromName(field_name)
        already_editing = layer.isEditable()
        if not already_editing:
            layer.startEditing()

        processed = 0
        repaired = 0
        skipped = 0

        try:
            for feature in layer.getFeatures():
                fid = feature.id()
                if not feature.hasGeometry():
                    layer.changeAttributeValue(fid, field_index, None)
                    skipped += 1
                    continue
                geom = feature.geometry()
                if not geom.isGeosValid():
                    geom = geom.makeValid()
                    if not geom or geom.isNull() or geom.isEmpty():
                        layer.changeAttributeValue(fid, field_index, None)
                        skipped += 1
                        continue
                    repaired += 1
                area_m2 = da.measureArea(geom)
                if math.isnan(area_m2):
                    layer.changeAttributeValue(fid, field_index, None)
                    skipped += 1
                    continue
                layer.changeAttributeValue(fid, field_index, round(area_m2 / 10000, 4))
                processed += 1

            if not already_editing:
                layer.commitChanges()

            msg = f"'{field_name}' populated for {processed}/{layer.featureCount()} features."
            if repaired:
                msg += f" {repaired} geometries auto-repaired."
            if skipped:
                msg += f" {skipped} skipped (null/unfixable geometry)."
            if already_editing:
                msg += " Layer in edit mode — commit manually."
            bar.pushMessage('Area_ha', msg, level=Qgis.Success, duration=8)

        except Exception as e:
            if not already_editing:
                layer.rollBack()
            bar.pushMessage('Area_ha', f'Error: {e}. Changes rolled back.', level=Qgis.Critical, duration=10)
